### ISSUE TITLE
email undefined

### ISSUE THREAD

**Issue by andrewzielinski** [thedavidprice/redwood-tutorial-test#10]
Running version d1dd46c1722a04ad37d9c73442648a313b403772 of the tutorial.
Getting undefined as the FieldError instead of the nice message.

![Screen Shot 2020-09-28 at 5 50 54 pm](https://user-images.githubusercontent.com/6296/94405140-7a720a80-01b3-11eb-84b3-8ec3c34d2eb0.png)

**Comment by thedavidprice** [comment]
Ah, thank you @andrewzielinski This code comes from our Redwood Tutorial. So I've created an issue in appropriate repo here https://github.com/redwoodjs/redwoodjs.com/issues/397
